### PR TITLE
Fix issue #4 errors on clean tasks

### PR DESCRIPTION
**Pull request by yinzara**

### CODE REVIEW

**Comment by yinzara** [comment]
@macsux Any chance we could get some love here? :-) I'd really love a version with this and .NET 6 (already merged) available on NuGet.  Would let us get rid of our custom branch in our build

**Review by macsux — APPROVED** [review]

**Comment by macsux** [comment]
Sorry, for some reason i got unwatched from repo so didn't see pr come in.
I'll merge it soon. Seems like there is an issue with how I did naming for
test container that doesn't like pr. I'll fix that issue separately

**Comment by yinzara** [comment]
I really appreciate that. Thank you for putting effort into creating this!   While it's super useful for just a single .NET Docker project build, it has other great uses.  We use it in a mono-repo setup where we separate out the dependencies for the entire repo into their own Docker image so that our service images only have local project code and this library was essential to making that possible.

**Comment by macsux** [comment]
Something got broken, build is failing. Didn't have time to look at it and
I'm on vacation next week. I'll figure it out when I'm back

**Pull request merged**
