### PR TITLE
Add support for comma separated list of layers

### PR DESCRIPTION
**Pull request by yinzara**

### CODE REVIEW

**Review by macsux — COMMENTED** [review]
Can you please describe a use-case on when someone would want to publish a combination of multiple layers that is not `All`?

**Comment by yinzara** [comment]
Use case:
I use this in a monorepo where many projects all share the same set of external dependencies.  How the repo builds is by a special initial project that only has dependencies and no code that I build a Docer image from. 

I then build each microservice separately and their Dockerfiles use the dependencies Docker image as their has the benefit of reducing my image sizes substantially by not duplicating the shared DLLs across multiple projects. 

In this case,  I would build the initial image using two of the layers and each microservice using the other two.

**Comment by macsux** [comment]
Ok, I'll integrate this into the next version, hopefully, get it out over
the next few days.

**Comment by macsux** [comment]
This feature has been added to latest version

**Pull request closed without merging**
